export const COUNTRIES = [
    { code: 'AF', label: 'Afghanistan', flag: '🇦🇫', dialCode: '+93' },
    { code: 'AL', label: 'Albanie', flag: '🇦🇱', dialCode: '+355' },
    { code: 'DZ', label: 'Algérie', flag: '🇩🇿', dialCode: '+213' },
    { code: 'AD', label: 'Andorre', flag: '🇦🇩', dialCode: '+376' },
    { code: 'AO', label: 'Angola', flag: '🇦🇴', dialCode: '+244' },
    { code: 'AG', label: 'Antigua-et-Barbuda', flag: '🇦🇬', dialCode: '+1-268' },
    { code: 'AR', label: 'Argentine', flag: '🇦🇷', dialCode: '+54' },
    { code: 'AM', label: 'Arménie', flag: '🇦🇲', dialCode: '+374' },
    { code: 'AU', label: 'Australie', flag: '🇦🇺', dialCode: '+61' },
    { code: 'AT', label: 'Autriche', flag: '🇦🇹', dialCode: '+43' },
    { code: 'AZ', label: 'Azerbaïdjan', flag: '🇦🇿', dialCode: '+994' },
    { code: 'BS', label: 'Bahamas', flag: '🇧🇸', dialCode: '+1-242' },
    { code: 'BH', label: 'Bahreïn', flag: '🇧🇭', dialCode: '+973' },
    { code: 'BD', label: 'Bangladesh', flag: '🇧🇩', dialCode: '+880' },
    { code: 'BB', label: 'Barbade', flag: '🇧🇧', dialCode: '+1-246' },
    { code: 'BY', label: 'Biélorussie', flag: '🇧🇾', dialCode: '+375' },
    { code: 'BE', label: 'Belgique', flag: '🇧🇪', dialCode: '+32' },
    { code: 'BZ', label: 'Belize', flag: '🇧🇿', dialCode: '+501' },
    { code: 'BJ', label: 'Bénin', flag: '🇧🇯', dialCode: '+229' },
    { code: 'BT', label: 'Bhoutan', flag: '🇧🇹', dialCode: '+975' },
    { code: 'BO', label: 'Bolivie', flag: '🇧🇴', dialCode: '+591' },
    { code: 'BA', label: 'Bosnie-Herzégovine', flag: '🇧🇦', dialCode: '+387' },
    { code: 'BW', label: 'Botswana', flag: '🇧🇼', dialCode: '+267' },
    { code: 'BR', label: 'Brésil', flag: '🇧🇷', dialCode: '+55' },
    { code: 'BN', label: 'Brunei', flag: '🇧🇳', dialCode: '+673' },
    { code: 'BG', label: 'Bulgarie', flag: '🇧🇬', dialCode: '+359' },
    { code: 'BF', label: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226' },
    { code: 'BI', label: 'Burundi', flag: '🇧🇮', dialCode: '+257' },
    { code: 'KH', label: 'Cambodge', flag: '🇰🇭', dialCode: '+855' },
    { code: 'CM', label: 'Cameroun', flag: '🇨🇲', dialCode: '+237' },
    { code: 'CA', label: 'Canada', flag: '🇨🇦', dialCode: '+1' },
    { code: 'CV', label: 'Cap-Vert', flag: '🇨🇻', dialCode: '+238' },
    { code: 'CF', label: 'République centrafricaine', flag: '🇨🇫', dialCode: '+236' },
    { code: 'TD', label: 'Tchad', flag: '🇹🇩', dialCode: '+235' },
    { code: 'CL', label: 'Chili', flag: '🇨🇱', dialCode: '+56' },
    { code: 'CN', label: 'Chine', flag: '🇨🇳', dialCode: '+86' },
    { code: 'CO', label: 'Colombie', flag: '🇨🇴', dialCode: '+57' },
    { code: 'KM', label: 'Comores', flag: '🇰🇲', dialCode: '+269' },
    { code: 'CG', label: 'Congo-Brazzaville', flag: '🇨🇬', dialCode: '+242' },
    { code: 'CD', label: 'Congo-Kinshasa', flag: '🇨🇩', dialCode: '+243' },
    { code: 'CR', label: 'Costa Rica', flag: '🇨🇷', dialCode: '+506' },
    { code: 'CI', label: "Côte d'Ivoire", flag: '🇨🇮', dialCode: '+225' },
    { code: 'HR', label: 'Croatie', flag: '🇭🇷', dialCode: '+385' },
    { code: 'CU', label: 'Cuba', flag: '🇨🇺', dialCode: '+53' },
    { code: 'CY', label: 'Chypre', flag: '🇨🇾', dialCode: '+357' },
    { code: 'CZ', label: 'République tchèque', flag: '🇨🇿', dialCode: '+420' },
    { code: 'DK', label: 'Danemark', flag: '🇩🇰', dialCode: '+45' },
    { code: 'DJ', label: 'Djibouti', flag: '🇩🇯', dialCode: '+253' },
    { code: 'DM', label: 'Dominique', flag: '🇩🇲', dialCode: '+1-767' },
    { code: 'DO', label: 'République dominicaine', flag: '🇩🇴', dialCode: '+1-809' },
    { code: 'EC', label: 'Équateur', flag: '🇪🇨', dialCode: '+593' },
    { code: 'EG', label: 'Égypte', flag: '🇪🇬', dialCode: '+20' },
    { code: 'SV', label: 'Salvador', flag: '🇸🇻', dialCode: '+503' },
    { code: 'GQ', label: 'Guinée équatoriale', flag: '🇬🇶', dialCode: '+240' },
    { code: 'ER', label: 'Érythrée', flag: '🇪🇷', dialCode: '+291' },
    { code: 'EE', label: 'Estonie', flag: '🇪🇪', dialCode: '+372' },
    { code: 'SZ', label: 'Eswatini', flag: '🇸🇿', dialCode: '+268' },
    { code: 'ET', label: 'Éthiopie', flag: '🇪🇹', dialCode: '+251' },
    { code: 'FJ', label: 'Fidji', flag: '🇫🇯', dialCode: '+679' },
    { code: 'FI', label: 'Finlande', flag: '🇫🇮', dialCode: '+358' },
    { code: 'FR', label: 'France', flag: '🇫🇷', dialCode: '+33' },
    { code: 'GA', label: 'Gabon', flag: '🇬🇦', dialCode: '+241' },
    { code: 'GM', label: 'Gambie', flag: '🇬🇲', dialCode: '+220' },
    { code: 'GE', label: 'Géorgie', flag: '🇬🇪', dialCode: '+995' },
    { code: 'DE', label: 'Allemagne', flag: '🇩🇪', dialCode: '+49' },
    { code: 'GH', label: 'Ghana', flag: '🇬🇭', dialCode: '+233' },
    { code: 'GR', label: 'Grèce', flag: '🇬🇷', dialCode: '+30' },
    { code: 'GD', label: 'Grenade', flag: '🇬🇩', dialCode: '+1-473' },
    { code: 'GT', label: 'Guatemala', flag: '🇬🇹', dialCode: '+502' },
    { code: 'GN', label: 'Guinée', flag: '🇬🇳', dialCode: '+224' },
    { code: 'GW', label: 'Guinée-Bissau', flag: '🇬🇼', dialCode: '+245' },
    { code: 'GY', label: 'Guyana', flag: '🇬🇾', dialCode: '+592' },
    { code: 'HT', label: 'Haïti', flag: '🇭🇹', dialCode: '+509' },
    { code: 'HN', label: 'Honduras', flag: '🇭🇳', dialCode: '+504' },
    { code: 'HU', label: 'Hongrie', flag: '🇭🇺', dialCode: '+36' },
    { code: 'IS', label: 'Islande', flag: '🇮🇸', dialCode: '+354' },
    { code: 'IN', label: 'Inde', flag: '🇮🇳', dialCode: '+91' },
    { code: 'ID', label: 'Indonésie', flag: '🇮🇩', dialCode: '+62' },
    { code: 'IR', label: 'Iran', flag: '🇮🇷', dialCode: '+98' },
    { code: 'IQ', label: 'Irak', flag: '🇮🇶', dialCode: '+964' },
    { code: 'IE', label: 'Irlande', flag: '🇮🇪', dialCode: '+353' },
    { code: 'IL', label: 'Israël', flag: '🇮🇱', dialCode: '+972' },
    { code: 'IT', label: 'Italie', flag: '🇮🇹', dialCode: '+39' },
    { code: 'JM', label: 'Jamaïque', flag: '🇯🇲', dialCode: '+1-876' },
    { code: 'JP', label: 'Japon', flag: '🇯🇵', dialCode: '+81' },
    { code: 'JO', label: 'Jordanie', flag: '🇯🇴', dialCode: '+962' },
    { code: 'KZ', label: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7' },
    { code: 'KE', label: 'Kenya', flag: '🇰🇪', dialCode: '+254' },
    { code: 'KI', label: 'Kiribati', flag: '🇰🇮', dialCode: '+686' },
    { code: 'KP', label: 'Corée du Nord', flag: '🇰🇵', dialCode: '+850' },
    { code: 'KR', label: 'Corée du Sud', flag: '🇰🇷', dialCode: '+82' },
    { code: 'KW', label: 'Koweït', flag: '🇰🇼', dialCode: '+965' },
    { code: 'KG', label: 'Kirghizistan', flag: '🇰🇬', dialCode: '+996' },
    { code: 'LA', label: 'Laos', flag: '🇱🇦', dialCode: '+856' },
    { code: 'LV', label: 'Lettonie', flag: '🇱🇻', dialCode: '+371' },
    { code: 'LB', label: 'Liban', flag: '🇱🇧', dialCode: '+961' },
    { code: 'LS', label: 'Lesotho', flag: '🇱🇸', dialCode: '+266' },
    { code: 'LR', label: 'Libéria', flag: '🇱🇷', dialCode: '+231' },
    { code: 'LY', label: 'Libye', flag: '🇱🇾', dialCode: '+218' },
    { code: 'LI', label: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423' },
    { code: 'LT', label: 'Lituanie', flag: '🇱🇹', dialCode: '+370' },
    { code: 'LU', label: 'Luxembourg', flag: '🇱🇺', dialCode: '+352' },
    { code: 'MG', label: 'Madagascar', flag: '🇲🇬', dialCode: '+261' },
    { code: 'MW', label: 'Malawi', flag: '🇲🇼', dialCode: '+265' },
    { code: 'MY', label: 'Malaisie', flag: '🇲🇾', dialCode: '+60' },
    { code: 'MV', label: 'Maldives', flag: '🇲🇻', dialCode: '+960' },
    { code: 'ML', label: 'Mali', flag: '🇲🇱', dialCode: '+223' },
    { code: 'MT', label: 'Malte', flag: '🇲🇹', dialCode: '+356' },
    { code: 'MH', label: 'Îles Marshall', flag: '🇲🇭', dialCode: '+692' },
    { code: 'MR', label: 'Mauritanie', flag: '🇲🇷', dialCode: '+222' },
    { code: 'MU', label: 'Maurice', flag: '🇲🇺', dialCode: '+230' },
    { code: 'MX', label: 'Mexique', flag: '🇲🇽', dialCode: '+52' },
    { code: 'FM', label: 'Micronésie', flag: '🇫🇲', dialCode: '+691' },
    { code: 'MD', label: 'Moldavie', flag: '🇲🇩', dialCode: '+373' },
    { code: 'MC', label: 'Monaco', flag: '🇲🇨', dialCode: '+377' },
    { code: 'MN', label: 'Mongolie', flag: '🇲🇳', dialCode: '+976' },
    { code: 'ME', label: 'Monténégro', flag: '🇲🇪', dialCode: '+382' },
    { code: 'MA', label: 'Maroc', flag: '🇲🇦', dialCode: '+212' },
    { code: 'MZ', label: 'Mozambique', flag: '🇲🇿', dialCode: '+258' },
    { code: 'MM', label: 'Birmanie', flag: '🇲🇲', dialCode: '+95' },
    { code: 'NA', label: 'Namibie', flag: '🇳🇦', dialCode: '+264' },
    { code: 'NR', label: 'Nauru', flag: '🇳🇷', dialCode: '+674' },
    { code: 'NP', label: 'Népal', flag: '🇳🇵', dialCode: '+977' },
    { code: 'NL', label: 'Pays-Bas', flag: '🇳🇱', dialCode: '+31' },
    { code: 'NZ', label: 'Nouvelle-Zélande', flag: '🇳🇿', dialCode: '+64' },
    { code: 'NI', label: 'Nicaragua', flag: '🇳🇮', dialCode: '+505' },
    { code: 'NE', label: 'Niger', flag: '🇳🇪', dialCode: '+227' },
    { code: 'NG', label: 'Nigéria', flag: '🇳🇬', dialCode: '+234' },
    { code: 'MK', label: 'Macédoine du Nord', flag: '🇲🇰', dialCode: '+389' },
    { code: 'NO', label: 'Norvège', flag: '🇳🇴', dialCode: '+47' },
    { code: 'OM', label: 'Oman', flag: '🇴🇲', dialCode: '+968' },
    { code: 'PK', label: 'Pakistan', flag: '🇵🇰', dialCode: '+92' },
    { code: 'PW', label: 'Palaos', flag: '🇵🇼', dialCode: '+680' },
    { code: 'PS', label: 'Palestine', flag: '🇵🇸', dialCode: '+970' },
    { code: 'PA', label: 'Panama', flag: '🇵🇦', dialCode: '+507' },
    { code: 'PG', label: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', dialCode: '+675' },
    { code: 'PY', label: 'Paraguay', flag: '🇵🇾', dialCode: '+595' },
    { code: 'PE', label: 'Pérou', flag: '🇵🇪', dialCode: '+51' },
    { code: 'PH', label: 'Philippines', flag: '🇵🇭', dialCode: '+63' },
    { code: 'PL', label: 'Pologne', flag: '🇵🇱', dialCode: '+48' },
    { code: 'PT', label: 'Portugal', flag: '🇵🇹', dialCode: '+351' },
    { code: 'QA', label: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
    { code: 'RO', label: 'Roumanie', flag: '🇷🇴', dialCode: '+40' },
    { code: 'RU', label: 'Russie', flag: '🇷🇺', dialCode: '+7' },
    { code: 'RW', label: 'Rwanda', flag: '🇷🇼', dialCode: '+250' },
    { code: 'KN', label: 'Saint-Christophe-et-Niévès', flag: '🇰🇳', dialCode: '+1-869' },
    { code: 'LC', label: 'Sainte-Lucie', flag: '🇱🇨', dialCode: '+1-758' },
    { code: 'VC', label: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨', dialCode: '+1-784' },
    { code: 'WS', label: 'Samoa', flag: '🇼🇸', dialCode: '+685' },
    { code: 'SM', label: 'Saint-Marin', flag: '🇸🇲', dialCode: '+378' },
    { code: 'ST', label: 'Sao Tomé-et-Principe', flag: '🇸🇹', dialCode: '+239' },
    { code: 'SA', label: 'Arabie saoudite', flag: '🇸🇦', dialCode: '+966' },
    { code: 'SN', label: 'Sénégal', flag: '🇸🇳', dialCode: '+221' },
    { code: 'RS', label: 'Serbie', flag: '🇷🇸', dialCode: '+381' },
    { code: 'SC', label: 'Seychelles', flag: '🇸🇨', dialCode: '+248' },
    { code: 'SL', label: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232' },
    { code: 'SG', label: 'Singapour', flag: '🇸🇬', dialCode: '+65' },
    { code: 'SK', label: 'Slovaquie', flag: '🇸🇰', dialCode: '+421' },
    { code: 'SI', label: 'Slovénie', flag: '🇸🇮', dialCode: '+386' },
    { code: 'SB', label: 'Îles Salomon', flag: '🇸🇧', dialCode: '+677' },
    { code: 'SO', label: 'Somalie', flag: '🇸🇴', dialCode: '+252' },
    { code: 'ZA', label: 'Afrique du Sud', flag: '🇿🇦', dialCode: '+27' },
    { code: 'SS', label: 'Soudan du Sud', flag: '🇸🇸', dialCode: '+211' },
    { code: 'ES', label: 'Espagne', flag: '🇪🇸', dialCode: '+34' },
    { code: 'LK', label: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94' },
    { code: 'SD', label: 'Soudan', flag: '🇸🇩', dialCode: '+249' },
    { code: 'SR', label: 'Suriname', flag: '🇸🇷', dialCode: '+597' },
    { code: 'SE', label: 'Suède', flag: '🇸🇪', dialCode: '+46' },
    { code: 'CH', label: 'Suisse', flag: '🇨🇭', dialCode: '+41' },
    { code: 'SY', label: 'Syrie', flag: '🇸🇾', dialCode: '+963' },
    { code: 'TW', label: 'Taïwan', flag: '🇹🇼', dialCode: '+886' },
    { code: 'TJ', label: 'Tadjikistan', flag: '🇹🇯', dialCode: '+992' },
    { code: 'TZ', label: 'Tanzanie', flag: '🇹🇿', dialCode: '+255' },
    { code: 'TH', label: 'Thaïlande', flag: '🇹🇭', dialCode: '+66' },
    { code: 'TL', label: 'Timor oriental', flag: '🇹🇱', dialCode: '+670' },
    { code: 'TG', label: 'Togo', flag: '🇹🇬', dialCode: '+228' },
    { code: 'TO', label: 'Tonga', flag: '🇹🇴', dialCode: '+676' },
    { code: 'TT', label: 'Trinité-et-Tobago', flag: '🇹🇹', dialCode: '+1-868' },
    { code: 'TN', label: 'Tunisie', flag: '🇹🇳', dialCode: '+216' },
    { code: 'TR', label: 'Turquie', flag: '🇹🇷', dialCode: '+90' },
    { code: 'TM', label: 'Turkménistan', flag: '🇹🇲', dialCode: '+993' },
    { code: 'TV', label: 'Tuvalu', flag: '🇹🇻', dialCode: '+688' },
    { code: 'UG', label: 'Ouganda', flag: '🇺🇬', dialCode: '+256' },
    { code: 'UA', label: 'Ukraine', flag: '🇺🇦', dialCode: '+380' },
    { code: 'AE', label: 'Émirats arabes unis', flag: '🇦🇪', dialCode: '+971' },
    { code: 'GB', label: 'Royaume-Uni', flag: '🇬🇧', dialCode: '+44' },
    { code: 'US', label: 'États-Unis', flag: '🇺🇸', dialCode: '+1' },
    { code: 'UY', label: 'Uruguay', flag: '🇺🇾', dialCode: '+598' },
    { code: 'UZ', label: 'Ouzbékistan', flag: '🇺🇿', dialCode: '+998' },
    { code: 'VU', label: 'Vanuatu', flag: '🇻🇺', dialCode: '+678' },
    { code: 'VA', label: 'Vatican', flag: '🇻🇦', dialCode: '+39' },
    { code: 'VE', label: 'Venezuela', flag: '🇻🇪', dialCode: '+58' },
    { code: 'VN', label: 'Vietnam', flag: '🇻🇳', dialCode: '+84' },
    { code: 'YE', label: 'Yémen', flag: '🇾🇪', dialCode: '+967' },
    { code: 'ZM', label: 'Zambie', flag: '🇿🇲', dialCode: '+260' },
    { code: 'ZW', label: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263' }
];
