export const COUNTRIES = [
    { code: 'AF', label: 'Afghanistan', flag: '🇦🇫' },
    { code: 'AL', label: 'Albanie', flag: '🇦🇱' },
    { code: 'DZ', label: 'Algérie', flag: '🇩🇿' },
    { code: 'AD', label: 'Andorre', flag: '🇦🇩' },
    { code: 'AO', label: 'Angola', flag: '🇦🇴' },
    { code: 'AG', label: 'Antigua-et-Barbuda', flag: '🇦🇬' },
    { code: 'AR', label: 'Argentine', flag: '🇦🇷' },
    { code: 'AM', label: 'Arménie', flag: '🇦🇲' },
    { code: 'AU', label: 'Australie', flag: '🇦🇺' },
    { code: 'AT', label: 'Autriche', flag: '🇦🇹' },
    { code: 'AZ', label: 'Azerbaïdjan', flag: '🇦🇿' },
    { code: 'BS', label: 'Bahamas', flag: '🇧🇸' },
    { code: 'BH', label: 'Bahreïn', flag: '🇧🇭' },
    { code: 'BD', label: 'Bangladesh', flag: '🇧🇩' },
    { code: 'BB', label: 'Barbade', flag: '🇧🇧' },
    { code: 'BY', label: 'Biélorussie', flag: '🇧🇾' },
    { code: 'BE', label: 'Belgique', flag: '🇧🇪' },
    { code: 'BZ', label: 'Belize', flag: '🇧🇿' },
    { code: 'BJ', label: 'Bénin', flag: '🇧🇯' },
    { code: 'BT', label: 'Bhoutan', flag: '🇧🇹' },
    { code: 'BO', label: 'Bolivie', flag: '🇧🇴' },
    { code: 'BA', label: 'Bosnie-Herzégovine', flag: '🇧🇦' },
    { code: 'BW', label: 'Botswana', flag: '🇧🇼' },
    { code: 'BR', label: 'Brésil', flag: '🇧🇷' },
    { code: 'BN', label: 'Brunei', flag: '🇧🇳' },
    { code: 'BG', label: 'Bulgarie', flag: '🇧🇬' },
    { code: 'BF', label: 'Burkina Faso', flag: '🇧🇫' },
    { code: 'BI', label: 'Burundi', flag: '🇧🇮' },
    { code: 'KH', label: 'Cambodge', flag: '🇰🇭' },
    { code: 'CM', label: 'Cameroun', flag: '🇨🇲' },
    { code: 'CA', label: 'Canada', flag: '🇨🇦' },
    { code: 'CV', label: 'Cap-Vert', flag: '🇨🇻' },
    { code: 'CF', label: 'République centrafricaine', flag: '🇨🇫' },
    { code: 'TD', label: 'Tchad', flag: '🇹🇩' },
    { code: 'CL', label: 'Chili', flag: '🇨🇱' },
    { code: 'CN', label: 'Chine', flag: '🇨🇳' },
    { code: 'CO', label: 'Colombie', flag: '🇨🇴' },
    { code: 'KM', label: 'Comores', flag: '🇰🇲' },
    { code: 'CG', label: 'Congo-Brazzaville', flag: '🇨🇬' },
    { code: 'CD', label: 'Congo-Kinshasa', flag: '🇨🇩' },
    { code: 'CR', label: 'Costa Rica', flag: '🇨🇷' },
    { code: 'CI', label: "Côte d'Ivoire", flag: '🇨🇮' },
    { code: 'HR', label: 'Croatie', flag: '🇭🇷' },
    { code: 'CU', label: 'Cuba', flag: '🇨🇺' },
    { code: 'CY', label: 'Chypre', flag: '🇨🇾' },
    { code: 'CZ', label: 'République tchèque', flag: '🇨🇿' },
    { code: 'DK', label: 'Danemark', flag: '🇩🇰' },
    { code: 'DJ', label: 'Djibouti', flag: '🇩🇯' },
    { code: 'DM', label: 'Dominique', flag: '🇩🇲' },
    { code: 'DO', label: 'République dominicaine', flag: '🇩🇴' },
    { code: 'EC', label: 'Équateur', flag: '🇪🇨' },
    { code: 'EG', label: 'Égypte', flag: '🇪🇬' },
    { code: 'SV', label: 'Salvador', flag: '🇸🇻' },
    { code: 'GQ', label: 'Guinée équatoriale', flag: '🇬🇶' },
    { code: 'ER', label: 'Érythrée', flag: '🇪🇷' },
    { code: 'EE', label: 'Estonie', flag: '🇪🇪' },
    { code: 'SZ', label: 'Eswatini', flag: '🇸🇿' },
    { code: 'ET', label: 'Éthiopie', flag: '🇪🇹' },
    { code: 'FJ', label: 'Fidji', flag: '🇫🇯' },
    { code: 'FI', label: 'Finlande', flag: '🇫🇮' },
    { code: 'FR', label: 'France', flag: '🇫🇷' },
    { code: 'GA', label: 'Gabon', flag: '🇬🇦' },
    { code: 'GM', label: 'Gambie', flag: '🇬🇲' },
    { code: 'GE', label: 'Géorgie', flag: '🇬🇪' },
    { code: 'DE', label: 'Allemagne', flag: '🇩🇪' },
    { code: 'GH', label: 'Ghana', flag: '🇬🇭' },
    { code: 'GR', label: 'Grèce', flag: '🇬🇷' },
    { code: 'GD', label: 'Grenade', flag: '🇬🇩' },
    { code: 'GT', label: 'Guatemala', flag: '🇬🇹' },
    { code: 'GN', label: 'Guinée', flag: '🇬🇳' },
    { code: 'GW', label: 'Guinée-Bissau', flag: '🇬🇼' },
    { code: 'GY', label: 'Guyana', flag: '🇬🇾' },
    { code: 'HT', label: 'Haïti', flag: '🇭🇹' },
    { code: 'HN', label: 'Honduras', flag: '🇭🇳' },
    { code: 'HU', label: 'Hongrie', flag: '🇭🇺' },
    { code: 'IS', label: 'Islande', flag: '🇮🇸' },
    { code: 'IN', label: 'Inde', flag: '🇮🇳' },
    { code: 'ID', label: 'Indonésie', flag: '🇮🇩' },
    { code: 'IR', label: 'Iran', flag: '🇮🇷' },
    { code: 'IQ', label: 'Irak', flag: '🇮🇶' },
    { code: 'IE', label: 'Irlande', flag: '🇮🇪' },
    { code: 'IL', label: 'Israël', flag: '🇮🇱' },
    { code: 'IT', label: 'Italie', flag: '🇮🇹' },
    { code: 'JM', label: 'Jamaïque', flag: '🇯🇲' },
    { code: 'JP', label: 'Japon', flag: '🇯🇵' },
    { code: 'JO', label: 'Jordanie', flag: '🇯🇴' },
    { code: 'KZ', label: 'Kazakhstan', flag: '🇰🇿' },
    { code: 'KE', label: 'Kenya', flag: '🇰🇪' },
    { code: 'KI', label: 'Kiribati', flag: '🇰🇮' },
    { code: 'KP', label: 'Corée du Nord', flag: '🇰🇵' },
    { code: 'KR', label: 'Corée du Sud', flag: '🇰🇷' },
    { code: 'KW', label: 'Koweït', flag: '🇰🇼' },
    { code: 'KG', label: 'Kirghizistan', flag: '🇰🇬' },
    { code: 'LA', label: 'Laos', flag: '🇱🇦' },
    { code: 'LV', label: 'Lettonie', flag: '🇱🇻' },
    { code: 'LB', label: 'Liban', flag: '🇱🇧' },
    { code: 'LS', label: 'Lesotho', flag: '🇱🇸' },
    { code: 'LR', label: 'Libéria', flag: '🇱🇷' },
    { code: 'LY', label: 'Libye', flag: '🇱🇾' },
    { code: 'LI', label: 'Liechtenstein', flag: '🇱🇮' },
    { code: 'LT', label: 'Lituanie', flag: '🇱🇹' },
    { code: 'LU', label: 'Luxembourg', flag: '🇱🇺' },
    { code: 'MG', label: 'Madagascar', flag: '🇲🇬' },
    { code: 'MW', label: 'Malawi', flag: '🇲🇼' },
    { code: 'MY', label: 'Malaisie', flag: '🇲🇾' },
    { code: 'MV', label: 'Maldives', flag: '🇲🇻' },
    { code: 'ML', label: 'Mali', flag: '🇲🇱' },
    { code: 'MT', label: 'Malte', flag: '🇲🇹' },
    { code: 'MH', label: 'Îles Marshall', flag: '🇲🇭' },
    { code: 'MR', label: 'Mauritanie', flag: '🇲🇷' },
    { code: 'MU', label: 'Maurice', flag: '🇲🇺' },
    { code: 'MX', label: 'Mexique', flag: '🇲🇽' },
    { code: 'FM', label: 'Micronésie', flag: '🇫🇲' },
    { code: 'MD', label: 'Moldavie', flag: '🇲🇩' },
    { code: 'MC', label: 'Monaco', flag: '🇲🇨' },
    { code: 'MN', label: 'Mongolie', flag: '🇲🇳' },
    { code: 'ME', label: 'Monténégro', flag: '🇲🇪' },
    { code: 'MA', label: 'Maroc', flag: '🇲🇦' },
    { code: 'MZ', label: 'Mozambique', flag: '🇲🇿' },
    { code: 'MM', label: 'Birmanie', flag: '🇲🇲' },
    { code: 'NA', label: 'Namibie', flag: '🇳🇦' },
    { code: 'NR', label: 'Nauru', flag: '🇳🇷' },
    { code: 'NP', label: 'Népal', flag: '🇳🇵' },
    { code: 'NL', label: 'Pays-Bas', flag: '🇳🇱' },
    { code: 'NZ', label: 'Nouvelle-Zélande', flag: '🇳🇿' },
    { code: 'NI', label: 'Nicaragua', flag: '🇳🇮' },
    { code: 'NE', label: 'Niger', flag: '🇳🇪' },
    { code: 'NG', label: 'Nigéria', flag: '🇳🇬' },
    { code: 'MK', label: 'Macédoine du Nord', flag: '🇲🇰' },
    { code: 'NO', label: 'Norvège', flag: '🇳🇴' },
    { code: 'OM', label: 'Oman', flag: '🇴🇲' },
    { code: 'PK', label: 'Pakistan', flag: '🇵🇰' },
    { code: 'PW', label: 'Palaos', flag: '🇵🇼' },
    { code: 'PS', label: 'Palestine', flag: '🇵🇸' },
    { code: 'PA', label: 'Panama', flag: '🇵🇦' },
    { code: 'PG', label: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
    { code: 'PY', label: 'Paraguay', flag: '🇵🇾' },
    { code: 'PE', label: 'Pérou', flag: '🇵🇪' },
    { code: 'PH', label: 'Philippines', flag: '🇵🇭' },
    { code: 'PL', label: 'Pologne', flag: '🇵🇱' },
    { code: 'PT', label: 'Portugal', flag: '🇵🇹' },
    { code: 'QA', label: 'Qatar', flag: '🇶🇦' },
    { code: 'RO', label: 'Roumanie', flag: '🇷🇴' },
    { code: 'RU', label: 'Russie', flag: '🇷🇺' },
    { code: 'RW', label: 'Rwanda', flag: '🇷🇼' },
    { code: 'KN', label: 'Saint-Christophe-et-Niévès', flag: '🇰🇳' },
    { code: 'LC', label: 'Sainte-Lucie', flag: '🇱🇨' },
    { code: 'VC', label: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨' },
    { code: 'WS', label: 'Samoa', flag: '🇼🇸' },
    { code: 'SM', label: 'Saint-Marin', flag: '🇸🇲' },
    { code: 'ST', label: 'Sao Tomé-et-Principe', flag: '🇸🇹' },
    { code: 'SA', label: 'Arabie saoudite', flag: '🇸🇦' },
    { code: 'SN', label: 'Sénégal', flag: '🇸🇳' },
    { code: 'RS', label: 'Serbie', flag: '🇷🇸' },
    { code: 'SC', label: 'Seychelles', flag: '🇸🇨' },
    { code: 'SL', label: 'Sierra Leone', flag: '🇸🇱' },
    { code: 'SG', label: 'Singapour', flag: '🇸🇬' },
    { code: 'SK', label: 'Slovaquie', flag: '🇸🇰' },
    { code: 'SI', label: 'Slovénie', flag: '🇸🇮' },
    { code: 'SB', label: 'Îles Salomon', flag: '🇸🇧' },
    { code: 'SO', label: 'Somalie', flag: '🇸🇴' },
    { code: 'ZA', label: 'Afrique du Sud', flag: '🇿🇦' },
    { code: 'SS', label: 'Soudan du Sud', flag: '🇸🇸' },
    { code: 'ES', label: 'Espagne', flag: '🇪🇸' },
    { code: 'LK', label: 'Sri Lanka', flag: '🇱🇰' },
    { code: 'SD', label: 'Soudan', flag: '🇸🇩' },
    { code: 'SR', label: 'Suriname', flag: '🇸🇷' },
    { code: 'SE', label: 'Suède', flag: '🇸🇪' },
    { code: 'CH', label: 'Suisse', flag: '🇨🇭' },
    { code: 'SY', label: 'Syrie', flag: '🇸🇾' },
    { code: 'TW', label: 'Taïwan', flag: '🇹🇼' },
    { code: 'TJ', label: 'Tadjikistan', flag: '🇹🇯' },
    { code: 'TZ', label: 'Tanzanie', flag: '🇹🇿' },
    { code: 'TH', label: 'Thaïlande', flag: '🇹🇭' },
    { code: 'TL', label: 'Timor oriental', flag: '🇹🇱' },
    { code: 'TG', label: 'Togo', flag: '🇹🇬' },
    { code: 'TO', label: 'Tonga', flag: '🇹🇴' },
    { code: 'TT', label: 'Trinité-et-Tobago', flag: '🇹🇹' },
    { code: 'TN', label: 'Tunisie', flag: '🇹🇳' },
    { code: 'TR', label: 'Turquie', flag: '🇹🇷' },
    { code: 'TM', label: 'Turkménistan', flag: '🇹🇲' },
    { code: 'TV', label: 'Tuvalu', flag: '🇹🇻' },
    { code: 'UG', label: 'Ouganda', flag: '🇺🇬' },
    { code: 'UA', label: 'Ukraine', flag: '🇺🇦' },
    { code: 'AE', label: 'Émirats arabes unis', flag: '🇦🇪' },
    { code: 'GB', label: 'Royaume-Uni', flag: '🇬🇧' },
    { code: 'US', label: 'États-Unis', flag: '🇺🇸' },
    { code: 'UY', label: 'Uruguay', flag: '🇺🇾' },
    { code: 'UZ', label: 'Ouzbékistan', flag: '🇺🇿' },
    { code: 'VU', label: 'Vanuatu', flag: '🇻🇺' },
    { code: 'VA', label: 'Vatican', flag: '🇻🇦' },
    { code: 'VE', label: 'Venezuela', flag: '🇻🇪' },
    { code: 'VN', label: 'Vietnam', flag: '🇻🇳' },
    { code: 'YE', label: 'Yémen', flag: '🇾🇪' },
    { code: 'ZM', label: 'Zambie', flag: '🇿🇲' },
    { code: 'ZW', label: 'Zimbabwe', flag: '🇿🇼' }
];
